app/urls.py
from django.urls import path
from app.views import (acceuil, ExporterExcelView,
                       EcarType, EtudiantForm, CoursForm, NoteForm,NoteUP,NoteD)

app_name = "app"

urlpatterns = [
    path('', acceuil.as_view(), name='acceuil'),
    path('exporter_excel/', ExporterExcelView.as_view(), name='exporter_excel'),
    path('ecartype/', EcarType, name='detail'),
    path('etudiant/', EtudiantForm.as_view(), name='etudiant'),
    path('cours/', CoursForm.as_view(), name='cours'),
    path('note/', NoteForm.as_view(), name='note'),
    path('note/<str:slug>/update/', NoteUP.as_view(), name='noteu'),
    path('note/<str:slug>/delete/', NoteD.as_view(), name='noted'),

]

projet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
import uuid
from slugify import slugify


class UserProfilesManager(BaseUserManager):
    """Modele de gestion des profils utilisateur"""

    def _create_user(self, username, email, Nom, Prenom, password=None, **extra_fields):
        """Crée un utilisateur de base"""
        if not email:
            raise ValueError('Un utilisateur doit avoir un email')

        email = self.normalize_email(email)
        user = self.model(username=username, email=email, Nom=Nom, Prenom=Prenom, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, Nom, Prenom, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        return self._create_user(username, email, Nom, Prenom, password, **extra_fields)

    def create_superuser(self, username, email, Nom, Prenom, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Le superutilisateur doit avoir is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Le superutilisateur doit avoir is_superuser=True.')

        return self._create_user(username, email, Nom, Prenom, password, **extra_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
    Nom = models.CharField(max_length=100)
    username = models.CharField(max_length=100, unique=True)
    Prenom = models.CharField(max_length=100)
    email = models.EmailField(max_length=255, unique=True)
    is_professeur = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfilesManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'Nom', 'Prenom']

    class Meta:
        verbose_name = "user profile"
        verbose_name_plural = "user profiles"
        ordering = ["username"]
        db_table = "user_profile"
        permissions = [
            ("can_view_profile", "Can view profile"),
            ("can_edit_profile", "Can edit profile"),
        ]

    @property
    def nom(self):
        return str(self.Nom).upper()

    @property
    def prenom(self):
        return str(self.Prenom).capitalize()

    def __str__(self):
        return self.Nom + " / " + self.Prenom
class Etudiant(models.Model):
    CodeEtudiant = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    NomEtudiant = models.CharField(max_length=100)
    PrenomEtudiant = models.CharField(max_length=100)
    Matricule = models.CharField(max_length=255, unique=True)
    DateNaissance = models.DateTimeField(blank=False)



    def __str__(self):
        return self.NomEtudiant

    @property
    def nom(self):
        return str(self.NomEtudiant).upper()

    @property
    def prenom(self):
        return str(self.PrenomEtudiant).capitalize()


class Cours(models.Model):
    CodeCours = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    NomCours = models.CharField(max_length=255,unique=True)
    Volume = models.IntegerField(blank=False)



    def __str__(self):
        return self.NomCours


class Note(models.Model):
    CodeNote = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    createdOn = models.DateTimeField(auto_now=True)
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE)
    note = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['etudiant', 'cours'], name='unique_etudiant_cours')
        ]

    def save(self, *args, **kwargs):
        # Génère un slug aléatoire à partir de etudiant et du cours
        slug_str = "%s %s" % (self.etudiant.PrenomEtudiant, self.cours.NomCours)
        slug_str = slug_str.replace(' ', '-').lower()
        # Ajoute un suffixe numérique si le slug existe déjà
        count = 1
        slug = slug_str
        while Note.objects.filter(slug=slug).exists():
            slug = "%s-%d" % (slug_str, count)
            count += 1
        self.slug = slug
        # Enregistre le modèle avec le slug généré
        super(Note, self).save(*args, **kwargs)


    def __str__(self):
        return f"{self.etudiant.PrenomEtudiant} {self.etudiant.NomEtudiant} - {self.cours.NomCours}: {self.note}"

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Etudiant, UserProfile


class EtudiantForm(forms.Form):
    etudiant = forms.ModelChoiceField(queryset=Etudiant.objects.all())


class SignupForm(UserCreationForm):
    is_professeur = forms.BooleanField(required=False)

    class Meta:
        model = UserProfile
        fields = UserCreationForm.Meta.fields + \
            ('username', 'Nom', 'Prenom', 'email', 'is_professeur')

    def try_save(self, request):
        user = super.save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        return user,None

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if UserProfile.objects.filter(email=email).exists():
            raise forms.ValidationError("Cet email est déjà utilisé.")
        return email

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>list etudiant</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <header class="header">
    <input type="checkbox" name id="btn" />
    <h2>Gestions des Etudiant</h2>
    <nav>
      <ul>
        <li>
          <a href="{% url 'app:acceuil' %}">Accueil</a>
        </li>
        {% if request.user.is_professeur %}

        <li>
          <a href="{% url 'app:detail' %}">ecart type</a>
        </li>

        <li>
          <label for="btn">
            <span class="btn">Ajouter</span>
          </label>
        </li>

        {% endif %} {% if request.user.is_authenticated %}
        <li>
          <a href="{% url 'account_logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% if request.user.is_professeur %}
    <div class="ajouter">
      <ul>
        <li>
          <a href="{% url 'app:etudiant' %}">Etudiant</a>
        </li>
        <li>
          <a href="{% url 'app:cours' %}">cours</a>
        </li>
        <li>
          <a href="{% url 'app:note' %}">note</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </header>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/cours.html
{% extends "base.html" %} {% block content%}
<div class="x">
  <form method="post" class="formE">
    {% csrf_token %}
    <h1>Formulaire Cours</h1>
    <div class="content">
      <div class="flex">
        <label for="id_NomCours">Nom du cous:</label>
        {{form.NomCours}}
      </div>
      <div class="flex">
        <label for="id_Volume ">Volume du cours:</label>
        {{form.Volume }}
      </div>
    </div>

    <input type="submit" class="send" value="Envoyer" />
  </form>
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html'%} {%block content%}
<div class="ecart">
  <div class="type">
    <form method="post" class="form">
      {% csrf_token %}
      <select name="etudiant">
        {% for etudiant in etudiants %}
        <option value="{{ etudiant.CodeEtudiant }}">
          {{ etudiant.NomEtudiant }} {{ etudiant.PrenomEtudiant }}
        </option>
        {% endfor %}
      </select>
      <input type="submit" value="Afficher" />
    </form>

    {% if selected_etudiant %}
    <p>
      L'écart type des notes de {{ selected_etudiant.NomEtudiant }}
      {{selected_etudiant.PrenomEtudiant }} est :
    </p>
    <span> {{selected_etudiant.ecart_type}} </span>
  </div>
</div>
{% endif %} {%endblock%}

templates/etudiant.html
{% extends "base.html" %} {% block content%}
<div class="x">
  <form method="post" class="formE">
    {% csrf_token %}
    <h1>Formulaire Etudiant</h1>
    <div class="content">
      <div class="flex">
        <label for="id_NomEtudiant">Nom:</label>
        {{form.NomEtudiant}}
      </div>
      <div class="flex">
        <label for="id_PrenomEtudiant">Prenom:</label>
        {{form.PrenomEtudiant}}
      </div>
      <div class="flex">
        <label for="id_Matricule">Matricule:</label>
        {{form.Matricule}}
      </div>
      <div class="flex">
        <label for="id_login">Date de Naissance:</label>
        <input
          type="date"
          name="DateNaissance"
          required
          id="id_DateNaissance"
        />
      </div>
    </div>

    <input type="submit" class="send" value="Envoyer" />
  </form>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %} {% block content %}{% include "list.html" %}
{%endblock %}

templates/list.html
<form method="get" class="search">
  <input type="text" name="q" placeholder="Search..." />
  <input type="submit" value="Search" />
</form>

<table>
  <tr>
    <th>Nom de l'étudiant</th>
    <th>Prénom de l'étudiant</th>
    <th>Matricule de l'étudiant</th>
    <th>cours</th>
    <th>note</th>
    <th>date d'attribution</th>
  </tr>
  {% for i in form %}
  <tr>
    <td>{{ i.etudiant.nom }}</td
    <td>{{ i.etudiant.prenom }}</td>
    <td>{{ i.etudiant.Matricule }}</td>
    <td>{{i.cours}}</td>
    <td>>
      {{i.note}} {% if request.user.is_professeur %}
      <a href="{% url 'app:noteu' slug=i.slug  %}">modifie</a>
      <a href="{% url 'app:noted' slug=i.slug  %}">supprime</a>
      {% endif %}
    </td>
    <td>{{i.createdOn}}</td>
  </tr>
  {% endfor %}
</table>
<button onclick="location.href='{% url 'app:exporter_excel' %}'">
  Exporter en Excel
</button>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

templates/note.html
{% extends "base.html" %} {% block content%}

<div class="x">
  <form method="post" class="formE">
    {% csrf_token %}
    <h1>Formulaire Note</h1>
    <div class="content">
      <div class="flex">
        <label for="id_etudiant">L'etudiant:</label>
        {{form.etudiant}}
      </div>
      <div class="flex">
        <label for="id_cours ">Cours:</label>
        {{form.cours }}
      </div>
      <div class="flex">
        <label for="id_note ">note:</label>
        {{form.note }}
      </div>
    </div>

    <input type="submit" class="send" value="Envoyer" />
  </form>
</div>
{% endblock %}

templates/noted.html
{% extends 'base.html' %}
{% block content %}
<h1>supprime la note</h1>
<form method="POST" class="formE">
    {% csrf_token%}
    <p> vous etes sur de vouloir supprime cette note "{{ note }}" ?</p>

    <input type="submit" class="btn btn-delete" value="oui, supprime">
</form>
{% endblock %}

templates/noteu.html
{% extends "base.html" %} {% block content%}

<div class="x">
  <form method="post" class="formE">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="send" value="Edite" />
  </form>
</div>
{% endblock %}